version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  worker:
    build: ./backend
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file: ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
